// server/controllers/orderController.js
const orderService = require('../services/orderService');

exports.createCheckoutSession = async (req, res) => {
    try {
        // Pass the heavy lifting to the service
        const url = await orderService.createCheckoutSession(req.user.id, req.user.email);
        
        // Send the result back to the frontend
        res.json({ url });
    } catch (error) {
        console.error("Stripe Error:", error);
        // Send the specific error message generated by the service
        res.status(400).json({ error: error.message || "Failed to create checkout session." });
    }
};

// Endpoint to handle the return from Stripe
exports.verifyPayment = async (req, res) => {
    try {
        // Grab the session_id from the URL query parameters
        const { session_id } = req.query;
        
        if (!session_id) {
            return res.status(400).json({ error: "Session ID is required" });
        }

        // Tell the service to verify it
        const order = await orderService.verifyAndCompleteOrder(session_id, req.user.id);
        
        res.json({ success: true, order });
    } catch (error) {
        console.error("Verification Error:", error);
        res.status(400).json({ success: false, error: error.message || "Failed to verify payment." });
    }
};